import type { Metadata } from "next";
import { MenuItem, Header, Footer } from "@/app/ui/hamberger-menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const menu: MenuItem[] = [
  { id: "0", title: "About", path: "/hamberger_menu/about" },
  { id: "1", title: "Solutions", path: "/hamberger_menu/solutions" },
  { id: "2", title: "Pricing", path: "/hamberger_menu/pricing" },
  { id: "3", title: "Resources", path: "/hamberger_menu/resources" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-zinc-700">
      <Header title={<div>The Company</div>} menuItems={menu} />
      {children}
      <Footer
        text={<div>2025 TheCompany . All Rights Reserved.</div>}
        menuItems={menu}
      />
    </div>
  );
}
