import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "@/app/ui/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer position="top-right">{children}</ToastContainer>
      </body>
    </html>
  );
}
